### PR TITLE
fix propTypes and compatible with 0.30.x react-native in android

### PR DESCRIPTION
**Pull request by SyMind**

### CODE REVIEW

**Comment by mochixuan** [comment]
Thank you for reminding me that the propTypes word is misspelled.

I saw the three files you submitted. The first file was spelled and I have changed it. The second file, Android and iOS, plus shadows are temporarily not added. The drag and drop of today's headlines is not shaded. If it is a single line drag and drop, it can be added. The third file does not need to be moved.

**Comment by SyMind** [comment]
not plus shadows, zIndex not supported in react-native 3.x.x version on Android, use elevation to compatible.

**Comment by mochixuan** [comment]
react-native最新版是react-native@0.60.x，rn没发展到3.x.x是不是说的是0.3.0之前？

**Comment by SyMind** [comment]
your are right! i write it wrongly.

**Pull request closed without merging**
